#pragma once



#if defined(_DEBUG)
// ToDo: Create platform independent debugger breakpoint
#define YAOOSL_FORCE_BREAK()
#else
#define YAOOSL_FORCE_BREAK()
#endif
#pragma region PRINT__YAOOSL_MTHD_PUSH_VALUE
#define PRINT__YAOOSL_MTHD_PUSH_VALUE_PROTO(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME)\
bool yaoosl_ ## PREFIX ## _push_ ## TARGETNAME(OBJTYPE OBJNAME, TARGETTYPE TARGETNAME)
#define PRINT__YAOOSL_MTHD_PUSH_VALUE_BODY_HEAD(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
    TARGETTYPE* FIELDNAME ## _ptr;\
    size_t size;\
    if (!OBJNAME || !TARGETNAME)\
    {\
        return false;\
    }
#define PRINT__YAOOSL_MTHD_PUSH_VALUE_BODY(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
    if (OBJNAME->FIELDNAME ## _size == OBJNAME->FIELDNAME ## _capacity)\
    {\
        size = (size_t)OBJNAME->FIELDNAME ## _capacity * (size_t)OBJNAME->FIELDNAME ## _capacity + 1;\
        if (size > (((size_t)1) << (sizeof(OBJNAME->FIELDNAME) + 1)) - 1) { return false; }\
        FIELDNAME ## _ptr = realloc(OBJNAME->FIELDNAME, sizeof(TARGETTYPE) * size);\
        if (!FIELDNAME ## _ptr)\
        {\
            return false;\
        }\
        OBJNAME->FIELDNAME = FIELDNAME ## _ptr;\
        OBJNAME->FIELDNAME ## _capacity = size;\
    }\
    OBJNAME->FIELDNAME ##[OBJNAME->FIELDNAME ## _size++] = TARGETNAME;
#define PRINT__YAOOSL_MTHD_PUSH_VALUE(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
PRINT__YAOOSL_MTHD_PUSH_VALUE_PROTO(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME)\
{\
    PRINT__YAOOSL_MTHD_PUSH_VALUE_BODY_HEAD(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
    PRINT__YAOOSL_MTHD_PUSH_VALUE_BODY(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
    return true;\
}
#define PRINT__YAOOSL_MTHD_PUSH_VALUE2_BODY_HEAD(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
    TARGETTYPE* FIELDNAME ## _ptr;\
    size_t size;\
    if (!OBJNAME)\
    {\
        return false;\
    }
#define PRINT__YAOOSL_MTHD_PUSH_VALUE2_BODY(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
    if (OBJNAME->FIELDNAME ## _size == OBJNAME->FIELDNAME ## _capacity)\
    {\
        size = (size_t)OBJNAME->FIELDNAME ## _capacity * (size_t)OBJNAME->FIELDNAME ## _capacity + 1;\
        if (size > (((size_t)1) << (sizeof(OBJNAME->FIELDNAME) + 1)) - 1) { return false; }\
        FIELDNAME ## _ptr = realloc(OBJNAME->FIELDNAME, sizeof(TARGETTYPE) * size);\
        if (!FIELDNAME ## _ptr) { return false; }\
        OBJNAME->FIELDNAME = FIELDNAME ## _ptr;\
        OBJNAME->FIELDNAME ## _capacity = size;\
    }\
    OBJNAME->FIELDNAME ##[OBJNAME->FIELDNAME ## _size++] = TARGETNAME;
#define PRINT__YAOOSL_MTHD_PUSH_VALUE2(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
PRINT__YAOOSL_MTHD_PUSH_VALUE_PROTO(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME)\
{\
    PRINT__YAOOSL_MTHD_PUSH_VALUE2_BODY_HEAD(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
    PRINT__YAOOSL_MTHD_PUSH_VALUE2_BODY(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
    return true;\
}
#pragma endregion
#define PRINT__YAOOSL_MTHD_POP_VALUE_PROTO(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME)\
TARGETTYPE yaoosl_ ## PREFIX ## _pop_ ## TARGETNAME(OBJTYPE OBJNAME)
#define PRINT__YAOOSL_MTHD_POP_VALUE(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
PRINT__YAOOSL_MTHD_POP_VALUE_PROTO(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME)\
{\
    if (!OBJNAME || OBJNAME->FIELDNAME ## _size == 0)\
    {\
        return NULL;\
    }\
    return OBJNAME->FIELDNAME[--OBJNAME->FIELDNAME ## _size];\
}
#define PRINT__YAOOSL_MTHD_POP_VALUE2(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME, FIELDNAME)\
PRINT__YAOOSL_MTHD_POP_VALUE_PROTO(PREFIX, OBJTYPE, OBJNAME, TARGETTYPE, TARGETNAME)\
{\
    TARGETTYPE TARGETNAME = {0};\
    if (!OBJNAME || OBJNAME->FIELDNAME ## _size == 0)\
    {\
        return TARGETNAME;\
    }\
    return OBJNAME->FIELDNAME[--OBJNAME->FIELDNAME ## _size];\
}


#define YAOOSL_STR(str) #str