#include "yaoosl_operators.h"
#include "string_op.h"

#include <string.h>


#define RET_OP_IF_MATCH(STR, OP)\
if (!str_cmp(STR, -1, #OP, (int)strlen(#OP)))\
{\
	return OP;\
}
#define OP_CASE_RET_STR(OP)\
case OP: return #OP

enum yaoosl_operator yaoosl_operator_from_string(const char* str)
{
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_ADD);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SUBTRACT);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_MULTIPLICATE);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_DIVIDE);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_AND);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_OR);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_XOR);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_BITSHIFT_LEFT);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_BITSHIFT_RIGHT);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_MODULO);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_INVERT);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_ADD);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_SUBTRACT);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_MULTIPLICATE);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_DIVIDE);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_AND);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_OR);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_XOR);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_BITSHIFT_LEFT);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_BITSHIFT_RIGHT);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_MODULO);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_INVERT);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_INCREASE);
	RET_OP_IF_MATCH(str, OP_ARITHMETICAL_SELF_DECREASE);
	RET_OP_IF_MATCH(str, OP_LOGICAL_NOT);
	RET_OP_IF_MATCH(str, OP_LOGICAL_AND);
	RET_OP_IF_MATCH(str, OP_LOGICAL_OR);
	RET_OP_IF_MATCH(str, OP_LOGICAL_EQUALS);
	RET_OP_IF_MATCH(str, OP_LOGICAL_EQUALS_NOT);
	RET_OP_IF_MATCH(str, OP_LOGICAL_LARGER_THEN);
	RET_OP_IF_MATCH(str, OP_LOGICAL_LARGER_THEN_OR_EQUAL);
	RET_OP_IF_MATCH(str, OP_LOGICAL_LESS_THEN);
	RET_OP_IF_MATCH(str, OP_LOGICAL_LESS_THEN_OR_EQUAL);
	RET_OP_IF_MATCH(str, OP_INDEX_GET);
	RET_OP_IF_MATCH(str, OP_INDEX_SET);
	return __INVALID;
}


const char* yaoosl_operator_to_string(enum yaoosl_operator operator)
{
	switch (operator)
	{
		OP_CASE_RET_STR(OP_ARITHMETICAL_ADD);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SUBTRACT);
		OP_CASE_RET_STR(OP_ARITHMETICAL_MULTIPLICATE);
		OP_CASE_RET_STR(OP_ARITHMETICAL_DIVIDE);
		OP_CASE_RET_STR(OP_ARITHMETICAL_AND);
		OP_CASE_RET_STR(OP_ARITHMETICAL_OR);
		OP_CASE_RET_STR(OP_ARITHMETICAL_XOR);
		OP_CASE_RET_STR(OP_ARITHMETICAL_BITSHIFT_LEFT);
		OP_CASE_RET_STR(OP_ARITHMETICAL_BITSHIFT_RIGHT);
		OP_CASE_RET_STR(OP_ARITHMETICAL_MODULO);
		OP_CASE_RET_STR(OP_ARITHMETICAL_INVERT);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_ADD);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_SUBTRACT);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_MULTIPLICATE);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_DIVIDE);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_AND);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_OR);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_XOR);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_BITSHIFT_LEFT);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_BITSHIFT_RIGHT);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_MODULO);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_INVERT);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_INCREASE);
		OP_CASE_RET_STR(OP_ARITHMETICAL_SELF_DECREASE);
		OP_CASE_RET_STR(OP_LOGICAL_NOT);
		OP_CASE_RET_STR(OP_LOGICAL_AND);
		OP_CASE_RET_STR(OP_LOGICAL_OR);
		OP_CASE_RET_STR(OP_LOGICAL_EQUALS);
		OP_CASE_RET_STR(OP_LOGICAL_EQUALS_NOT);
		OP_CASE_RET_STR(OP_LOGICAL_LARGER_THEN);
		OP_CASE_RET_STR(OP_LOGICAL_LARGER_THEN_OR_EQUAL);
		OP_CASE_RET_STR(OP_LOGICAL_LESS_THEN);
		OP_CASE_RET_STR(OP_LOGICAL_LESS_THEN_OR_EQUAL);
		OP_CASE_RET_STR(OP_INDEX_GET);
		OP_CASE_RET_STR(OP_INDEX_SET);
	default: return "";
	}
}
int yaoosl_operator_arg_count(enum yaoosl_operator operator)
{
	switch (operator)
	{
		// Arithmetical operations requiring two values: 
	case OP_ARITHMETICAL_ADD:
	case OP_ARITHMETICAL_SUBTRACT:
	case OP_ARITHMETICAL_MULTIPLICATE:
	case OP_ARITHMETICAL_DIVIDE:
	case OP_ARITHMETICAL_AND:
	case OP_ARITHMETICAL_OR:
	case OP_ARITHMETICAL_XOR:
	case OP_ARITHMETICAL_BITSHIFT_LEFT:
	case OP_ARITHMETICAL_BITSHIFT_RIGHT:
	case OP_ARITHMETICAL_MODULO:
		return 2;
		// Arithmetical operations requiring one value: 
	case OP_ARITHMETICAL_SELF_ADD:
	case OP_ARITHMETICAL_SELF_SUBTRACT:
	case OP_ARITHMETICAL_SELF_MULTIPLICATE:
	case OP_ARITHMETICAL_SELF_DIVIDE:
	case OP_ARITHMETICAL_SELF_AND:
	case OP_ARITHMETICAL_SELF_OR:
	case OP_ARITHMETICAL_SELF_XOR:
	case OP_ARITHMETICAL_SELF_BITSHIFT_LEFT:
	case OP_ARITHMETICAL_SELF_BITSHIFT_RIGHT:
	case OP_ARITHMETICAL_SELF_MODULO:
	case OP_ARITHMETICAL_INVERT:
		return 1;
		// Arithmetical operations requiring no value: 
	case OP_ARITHMETICAL_SELF_INCREASE:
	case OP_ARITHMETICAL_SELF_DECREASE:
	case OP_ARITHMETICAL_SELF_INVERT:
		return 0;
		// Logical operations requiring one value: 
	case OP_LOGICAL_NOT:
		return 1;
		// Logical operations requiring two values: 
	case OP_LOGICAL_AND:
	case OP_LOGICAL_OR:
	case OP_LOGICAL_EQUALS:
	case OP_LOGICAL_EQUALS_NOT:
	case OP_LOGICAL_LARGER_THEN:
	case OP_LOGICAL_LARGER_THEN_OR_EQUAL:
	case OP_LOGICAL_LESS_THEN:
	case OP_LOGICAL_LESS_THEN_OR_EQUAL:
		return 2;
	case OP_INDEX_SET:
		return 2;
	case OP_INDEX_GET:
		return 1;
	case __OPERATOR_MAX:
	case __INVALID:
	default:
		return -1;
	}
}
